In [1]:
import pandas as pd

In [2]:
wine_reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0) 
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
wine_reviews.price

0          NaN
1         15.0
2         14.0
3         13.0
4         65.0
          ...
129966    28.0
129967    75.0
129968    30.0
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

In [4]:
wine_reviews["country"]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: str

In [5]:
wine_reviews["country"][5]

'Spain'

In [6]:
wine_reviews.iloc[10]

country                                                                 US
description              Soft, supple plum envelopes an oaky structure ...
designation                                                 Mountain Cuvée
points                                                                  87
price                                                                 19.0
province                                                        California
region_1                                                       Napa Valley
region_2                                                              Napa
taster_name                                                 Virginie Boone
taster_twitter_handle                                              @vboone
title                    Kirkland Signature 2011 Mountain Cuvée Caberne...
variety                                                 Cabernet Sauvignon
winery                                                  Kirkland Signature
Name: 10, dtype: object

In [7]:
wine_reviews.iloc[:,:3]

,country,description,designation
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block
...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese
129967,US,Citation is given as much as a decade of bottl...,NaN
129968,France,Well-drained gravel soil gives this wine its c...,Kritt
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline

In [8]:
wine_reviews.iloc[:5, :3]

,country,description,designation
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block

In [9]:
wine_reviews.loc[0, "description"]

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [10]:
wine_reviews.loc[:, ["country", "description"]]

         country                                        description
0          Italy  Aromas include tropical fruit, broom, brimston...
1       Portugal  This is ripe and fruity, a wine that is smooth...
2             US  Tart and snappy, the flavors of lime flesh and...
3             US  Pineapple rind, lemon pith and orange blossom ...
4             US  Much like the regular bottling from 2012, this...
...          ...                                                ...
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...
129967        US  Citation is given as much as a decade of bottl...
129968    France  Well-drained gravel soil gives this wine its c...
129969    France  A dry style of Pinot Gris, this is crisp with ...
129970    France  Big, rich and off-dry, this is powered by inte...

[129971 rows x 2 columns]

In [11]:
# wine_reviews.set_index("country", inplace= True)
# wine_reviews.head()

In [12]:
wine_reviews.country == "Italy"

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [13]:
wine_reviews.loc[wine_reviews.country == "Italy"]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [18]:
wine_reviews.loc[ (wine_reviews.country == "Italy") & (wine_reviews.points >= 95)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
350,Italy,"After a few minutes in the glass, this stunnin...",Vignolo Riserva,97,150.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Cavallotto 2010 Vignolo Riserva (Barolo),Nebbiolo,Cavallotto
361,Italy,"Enticing scents of ripe berry, underbrush, gri...",Simposio,95,60.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Bel Colle 2012 Simposio (Barolo),Nebbiolo,Bel Colle
1561,Italy,"Here's a “wow” wine on every level, with incre...",Guado al Tasso,98,102.0,Tuscany,Bolgheri Superiore,NaN,NaN,NaN,Marchesi Antinori 2008 Guado al Tasso (Bolghe...,Red Blend,Marchesi Antinori
1563,Italy,Recently implemented winemaker and cellar chan...,Sassicaia,97,220.0,Tuscany,Bolgheri Sassicaia,NaN,NaN,NaN,Tenuta San Guido 2008 Sassicaia (Bolgheri Sas...,Red Blend,Tenuta San Guido
1564,Italy,The 2008 Ornellaia delivers concentrated aroma...,Ornellaia,97,215.0,Tuscany,Bolgheri Superiore,NaN,NaN,NaN,Tenuta dell'Ornellaia 2008 Ornellaia (Bolgher...,Red Blend,Tenuta dell'Ornellaia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125836,Italy,You really can't beat the beauty of this Barol...,Cannubi Boschis,96,165.0,Piedmont,Barolo,NaN,NaN,NaN,Luciano Sandrone 2007 Cannubi Boschis (Barolo),Nebbiolo,Luciano Sandrone
125845,Italy,An exciting flagship wine from one of the best...,Cerequio Riserva,95,103.0,Piedmont,Barolo,NaN,NaN,NaN,Michele Chiarlo 2006 Cerequio Riserva (Barolo),Nebbiolo,Michele Chiarlo
125846,Italy,A tiny percentage of Barbera grapes accounts f...,Conteisa,95,240.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2008 Conteisa Nebbiolo (Langhe),Nebbiolo,Gaja
125847,Italy,Costa Russi presents a dark wall of ripe fruit...,Costa Russi,95,495.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2009 Costa Russi Nebbiolo (Langhe),Nebbiolo,Gaja
126240,Italy,Ben Ryé is always a fabulous dessert wine from...,Ben Ryé,95,40.0,Sicily & Sardinia,Passito di Pantelleria,NaN,NaN,NaN,Donnafugata 2008 Ben Ryé (Passito di Pantelle...,Zibibbo,Donnafugata

In [19]:
wine_reviews.loc[ (wine_reviews.country == "Italy") | (wine_reviews.points >= 95)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [21]:
wine_reviews.country.isin(["Italy", "France"])

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968     True
129969     True
129970     True
Name: country, Length: 129971, dtype: bool

In [22]:
wine_reviews.loc[wine_reviews.country.isin(["Italy", "France"])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [23]:
wine_reviews.price.notnull()

0         False
1          True
2          True
3          True
4          True
          ...
129966     True
129967     True
129968     True
129969     True
129970     True
Name: price, Length: 129971, dtype: bool

In [24]:
wine_reviews.loc[wine_reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [25]:
wine_reviews.price.isnull()

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: price, Length: 129971, dtype: bool

In [26]:
wine_reviews.loc[wine_reviews.price.isnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Caparzo 2006 Doga delle Clavule (Morellino di...,Sangiovese,Caparzo
129860,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portuguese Red,Quinta da Pacheca
129863,Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Seacampo 2011 Reserva Red (Dão),Portuguese Red,Seacampo
129893,Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Le Mandolare 2015 Corte Menini (Soave Classico),Garganega,Le Mandolare
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart

### `isnull()` vs `notnull()` in pandas

Both functions are used to **detect missing values (NaN / None)** in pandas.

---

#### `isnull()`

- Returns **True where the value is missing**
- Returns **False where the value exists**

Example:

```python
df.isnull()
```

| value | result |
|------|--------|
| 10 | False |
| NaN | True |
| "wine" | False |

So it answers: **"Is this value missing?"**

---

#### `notnull()`

- Returns **True where the value exists**
- Returns **False where the value is missing**

Example:

```python
df.notnull()
```

| value | result |
|------|--------|
| 10 | True |
| NaN | False |
| "wine" | True |

So it answers: **"Is this value present?"**

---

#### Relationship

They are exact opposites:

```python
df.notnull() == ~df.isnull()
```

---

#### Common usage examples

Filter rows **with missing values**:

```python
df[df.price.isnull()]
```

Filter rows **without missing values**:

```python
df[df.price.notnull()]
```

---

✅ **Summary**

- `isnull()` → finds **missing values**
- `notnull()` → finds **non-missing values**

In [27]:
wine_reviews["critic"] = "Bad"
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Bad
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Bad
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Bad
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Bad
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Bad

# Exercises

## 1.

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [28]:
desc = wine_reviews["description"]
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: str

Follow-up question: what type of object is `desc`? If you're not sure, you can check by calling Python's `type` function: `type(desc)`.

In [29]:
type(desc)

pandas.Series

## 2.

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [30]:
first_description = desc[0]
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

### `loc` vs `iloc` in pandas

The main difference between `loc` and `iloc` is **how rows and columns are selected**.

| Method | Selects by | Uses DataFrame index? |
|------|------|------|
| `loc` | **Label-based indexing** | ✅ Yes |
| `iloc` | **Position-based indexing** | ❌ No (uses integer position) |

---

### `loc` → Uses the **actual index labels**

If your DataFrame index looks like this:

```python
index: [10, 20, 30]
```

Then:

```python
df.loc[20]
```

selects the row **whose index label is `20`**.

---

### `iloc` → Uses **row position (0-based)**

`iloc` ignores the index labels and uses the **row order**.

```python
df.iloc[1]
```

selects the **second row**, regardless of what the index label is.

---

### Example

DataFrame:

| index | country |
|------|------|
| 10 | Italy |
| 20 | France |
| 30 | Spain |

Using `loc`:

```python
df.loc[20]
```

➡ Returns the row with index **20** → France

Using `iloc`:

```python
df.iloc[1]
```

➡ Returns the row at **position 1** → France

---

### Important difference in slicing

```python
df.loc[0:3]   # includes 3
df.iloc[0:3]  # excludes 3
```

- `loc` slicing is **inclusive**
- `iloc` slicing follows **normal Python slicing (exclusive end)**

---

### Quick way to remember

- **`loc` → location by label**
- **`iloc` → integer location (position)**

## 3. 

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [31]:
first_row = wine_reviews.iloc[0,:]
first_row

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
critic                                                                 Bad
Name: 0, dtype: object

## 4.

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [35]:
first_descriptions = wine_reviews["description"].iloc[:10]
first_descriptions

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: str

## 5.

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

In other words, generate the following DataFrame:

![](https://storage.googleapis.com/kaggle-media/learn/images/sHZvI1O.png)

In [39]:
# loc can work with : as well in columns. If you want to specify column, then you need labels instead of indices
sample_reviews = wine_reviews.loc[[1,2,3,5,8], :]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Bad
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Bad
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Bad
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,Bad
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel,Bad

In [40]:
# # loc can work with : as well in columns. If you want to specify column, then you need labels instead of indices
# sample_reviews = wine_reviews.loc[[1,2,3,5,8], :2] # Will give error
# sample_reviews

## 6.

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`. In other words, generate the following DataFrame:

![](https://storage.googleapis.com/kaggle-media/learn/images/FUCGiKP.png)

In [41]:
df = wine_reviews.loc[[0,1,10,100], ["country", "province", "region_1", "region_2"]]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

## 7.

Create a variable `df` containing the `country` and `variety` columns of the first 100 records. 

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the tutorial:

> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. 
`loc`, meanwhile, indexes inclusively. 

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.iloc[0:999]`.

In [43]:
df = wine_reviews.loc[0:99, ["country", "variety"]]
df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

## 8.

Create a DataFrame `italian_wines` containing reviews of wines made in `Italy`. Hint: `reviews.country` equals what?

In [47]:
italian_wines = wine_reviews.loc[wine_reviews["country"] == "Italy"]
italian_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Bad
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo,Bad
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte,Bad
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto,Bad
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti,Bad
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello,Bad
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera,Bad
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS,Bad
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano,Bad

## 9.

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [49]:
top_oceania_wines = wine_reviews.loc[(wine_reviews.points >= 95) & (wine_reviews.country.isin(["Australia", "New Zealand"]))]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards,Bad
346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards,Bad
348,Australia,Deep mahogany. Dried fig and black tea on the ...,Grand,97,100.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Grand Muscat (R...,Muscat,Chambers Rosewood Vineyards,Bad
349,Australia,"RunRig is always complex, and the 2012 doesn't...",RunRig,97,225.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 RunRig Shiraz-Viognier (Barossa),Shiraz-Viognier,Torbreck,Bad
356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill,Bad
360,Australia,Bacon and tapenade elements merge easily on th...,Descendant,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 Descendant Shiraz-Viognier (Baro...,Shiraz-Viognier,Torbreck,Bad
365,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield,Bad
14354,Australia,This wine's concentrated dark fruit shows in t...,Old Vine,95,60.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kaesler 2006 Old Vine Shiraz (Barossa Valley),Shiraz,Kaesler,Bad
16538,Australia,"Rich, dense and intense, this is a big, muscul...",The Family Tree,95,65.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Lambert 2013 The Family Tree Shiraz (Barossa V...,Shiraz,Lambert,Bad
28573,Australia,Astralis has become one of Australia's top col...,Astralis,95,350.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2005 Astralis Syrah (Clarendon),Syrah,Clarendon Hills,Bad
34502,Australia,This prodigious wine showcases Barossa's abili...,The Relic,98,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2006 The Relic Shiraz (Barossa Valley),Shiraz,Standish,Bad
34506,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2005 The Standish Single Vineyard Shi...,Shiraz,Standish,Bad
38988,Australia,Penfolds Bin 707 has leapt in quality over the...,Bin 707,95,200.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds,Bad
39059,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield,Bad
39961,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,NaN,NaN,Penfolds 1996 Grange Shiraz (South Australia),Shiraz,Penfolds,Bad
39962,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,NaN,NaN,Penfolds 1998 RWT Shiraz (Barossa Valley),Shiraz,Penfolds,Bad
45809,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2007 Astralis Syrah (Clarendon),Syrah,Clarendon Hills,Bad
56953,Australia,"This inky, embryonic wine deserves to be cella...",Grange,99,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2010 Grange Shiraz (South Australia),Shiraz,Penfolds,Bad
56956,Australia,You may have to scour the country to secure so...,Andelmonde,97,95.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2012 Andelmonde Shiraz (Barossa Valley),Shiraz,Standish,Bad
56957,Australia,Thorn Clarke has taken its Shiraz to a new lev...,Ron Thorn Single Vineyard,96,89.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Thorn Clarke 2012 Ron Thorn Single Vineyard Sh...,Shiraz,Thorn Clarke,Bad
56959,Australia,Is this the Yin to Grange's Yang? The wines ar...,Hill of Grace,96,820.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2010 Hill of Grace Shiraz (Eden Valley),Shiraz,Henschke,Bad
59977,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Hickinbotham 2013 The Peake Cabernet-Shiraz (M...,Cabernet-Shiraz,Hickinbotham,Bad
59984,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Joe Czerwinski,@JoeCz,Heartland 2013 One Red (Langhorne Creek),Red Blend,Heartland,Bad
67096,Australia,Just a tiny serving of this dark nectar will l...,Calliope Rare,98,86.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,R.L. Buller & Son NV Calliope Rare Tokay (Ruth...,Tokay,R.L. Buller & Son,Bad
67101,Australia,"This Muscat is the color of dark coffee, with ...",Rare,95,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards,Bad
76392,Australia,When the alcohol levels are reined in to appro...,Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2012 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill,Bad
77028,Australia,This has all the size and weight you've come t...,Grange,98,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2008 Grange Shiraz (South Australia),Shiraz,Penfolds,Bad
77036,Australia,RWT (unromantically derived from “Red Wine Tri...,RWT,96,150.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 RWT Shiraz (Barossa Valley),Shiraz,Penfolds,Bad
77037,Australia,Winemaker Dave Powell is no longer with Torbre...,RunRig,96,225.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 RunRig Shiraz-Viognier (Barossa ...,Shiraz-Viognier,Torbreck,Bad
77042,Australia,This is likely the most ageworthy Shiraz winem...,Eligo,95,100.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,John Duval Wines 2010 Eligo Shiraz (Barossa),Shiraz,John Duval Wines,Bad
77044,Australia,The fruit for this offering comes from the Gre...,R Reserve,95,105.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kilikanoon 2009 R Reserve Shiraz (Barossa Valley),Shiraz,Kilikanoon,Bad
77046,Australia,With aromas and flavors that range widely from...,The Factor,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck,Bad
83357,Australia,A throwback to the monster Shiraz style of old...,Grange,96,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2004 Grange Shiraz (South Australia),Shiraz,Penfolds,Bad
84815,Australia,The Factor is always one of Torbreck's biggest...,The Factor,95,125.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 The Factor Shiraz (Barossa),Shiraz,Torbreck,Bad
84816,Australia,"Nashwauk is Kaesler's McLaren Vale project, fi...",Beacon,95,145.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Nashwauk 2010 Beacon Shiraz (McLaren Vale),Shiraz,Nashwauk,Bad
87128,Australia,"This full-bodied, muscular Shiraz is built for...",Amery Vineyard Block 6,96,120.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Kay Brothers 2012 Amery Vineyard Block 6 Shira...,Shiraz,Kay Brothers,Bad
87137,Australia,Perhaps the best young wine I've tasted from M...,NaN,95,84.0,Western Australia,Margaret River,NaN,Joe Czerwinski,@JoeCz,Moss Wood 2011 Cabernet Sauvignon (Margaret Ri...,Cabernet Sauvignon,Moss Wood,Bad
87143,Australia,"This is wonderfully complex and aromatic, with...",St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2012 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield,Bad
91851,New Zealand,"This full-bodied, richly tannic wine delivers....",Homage,95,100.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Trinity Hill 2013 Homage Syrah (Hawke's Bay),Syrah,Trinity Hill,Bad
98386,Australia,One of the more approachable of the d'Arenberg...,Little Venice Single Vineyard,95,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 Little Venice Single Vineyard ...,Shiraz,D'Arenberg,Bad
99318,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2014 Mount Edelstone Vineyard Shiraz ...,Shiraz,Henschke,Bad
99330,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2014 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds,Bad
99340,Australia,"This rich, opulent wine carries its massive oa...",Les Amis,95,185.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 Les Amis Grenache (Barossa Valley),Grenache,Torbreck,Bad
109427,Australia,This wine is dark brown in hue with a greenish...,Rare,99,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards,Bad
109434,Australia,D'Arenberg's lineup of single-vineyard Shiraze...,The Swinging Malaysian Single Vineyard,96,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 The Swinging Malaysian Single ...,Shiraz,D'Arenberg,Bad
122421,Australia,"Despite this wine's weight and richness, it re...",Amon-Ra Unfiltered,96,110.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Amon-Ra Unfiltered Shiraz (Baros...,Shiraz,Glaetzer,Bad
122430,Australia,These blends are traditional in Australia—they...,Anaperenna,95,80.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Anaperenna Shiraz-Cabernet Sauvi...,Shiraz-Cabernet Sauvignon,Glaetzer,Bad
122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie,Bad
122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck,Bad