In [47]:
import pandas as pd

In [48]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0) 
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [49]:
reviews.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [50]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [51]:
reviews.country.describe()

count     129908
unique        43
top           US
freq       54504
Name: country, dtype: object

In [52]:
reviews.points.mean()

np.float64(88.44713820775404)

In [53]:
reviews.country.unique()

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                      nan,                 'Turkey',         'Czech Republic',
               'Slovenia',             'Luxembourg',                'Croatia',
                'Georgia',                'Uruguay',                'England',
                'Lebanon',                 'Serbia',                 'Brazil',
                'Moldova',                'Morocco',                   'Peru',
                  'India',               'Bulgaria',                 'Cyprus',
                'Armenia',            'Switzerland', 'Bosnia and Herzegovina',
                'Ukraine',               'Slovakia',              'Macedonia',
                  'China',                  'Egypt']
Length: 44, dtype: str

In [54]:
reviews.country.value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Serbia                       12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

Maps

A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

There are two mapping methods that you will use often.

map() is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

In [55]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p-review_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

In [56]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

In [57]:
reviews.apply(remean_points,axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### Understanding `axis` in pandas `apply()`

The `axis` parameter tells pandas **which direction to move across the DataFrame when applying a function**.

---

### Key idea

| axis | Direction pandas moves | Function applied to |
|-----|------------------------|---------------------|
| `axis=0` or `"index"` | ↓ down the rows | each **column** |
| `axis=1` or `"columns"` | → across the columns | each **row** |

---

### Example

```python
reviews.apply(remean_points, axis='columns')
```

What happens here:

- pandas **moves across the columns**
- collects the values from each column in that row
- passes the **entire row** to the function

So the function is applied **row-wise**.

Example DataFrame:

| country | points | price |
|--------|--------|-------|
| Italy | 90 | 25 |
| France | 88 | 30 |

`remean_points` will receive:

```
Row 1 → [Italy, 90, 25]
Row 2 → [France, 88, 30]
```

---

### Visual memory trick

```
axis = 0  ↓  (down rows)
operate on columns

axis = 1  →  (across columns)
operate on rows
```

---

### Another way to remember

If you write:

```python
axis='columns'
```

pandas **moves across columns**, which naturally processes **rows**.

---

### Quick rule

**`axis=1` → combine/use columns → operate on rows**

If we had called reviews.apply() with axis='index', then instead of passing a function to transform each row, we would need to give a function to transform each column.

Note that map() and apply() return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on. If we look at the first row of reviews, we can see that it still has its original points value.

In [58]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Pandas provides many common mapping operations as built-ins. For example, here's a faster way of remeaning our points column:

In [59]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In this code we are performing an operation between a lot of values on the left-hand side (everything in the Series) and a single value on the right-hand side (the mean value). Pandas looks at this expression and figures out that we must mean to subtract that mean value from every value in the dataset.

# Exercises

## 1.

What is the median of the `points` column in the `reviews` DataFrame?

In [60]:
reviews.points.median()

np.float64(88.0)

## 2. 
What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [61]:
reviews.country.unique()

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                      nan,                 'Turkey',         'Czech Republic',
               'Slovenia',             'Luxembourg',                'Croatia',
                'Georgia',                'Uruguay',                'England',
                'Lebanon',                 'Serbia',                 'Brazil',
                'Moldova',                'Morocco',                   'Peru',
                  'India',               'Bulgaria',                 'Cyprus',
                'Armenia',            'Switzerland', 'Bosnia and Herzegovina',
                'Ukraine',               'Slovakia',              'Macedonia',
                  'China',                  'Egypt']
Length: 44, dtype: str

In [62]:
reviews.country.dropna().unique()

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                 'Turkey',         'Czech Republic',               'Slovenia',
             'Luxembourg',                'Croatia',                'Georgia',
                'Uruguay',                'England',                'Lebanon',
                 'Serbia',                 'Brazil',                'Moldova',
                'Morocco',                   'Peru',                  'India',
               'Bulgaria',                 'Cyprus',                'Armenia',
            'Switzerland', 'Bosnia and Herzegovina',                'Ukraine',
               'Slovakia',              'Macedonia',                  'China',
                  'Egypt']
Length: 43, dtype: str

How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [63]:
reviews_per_country = reviews["country"].value_counts()
reviews_per_country

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Serbia                       12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

## 4.
Create variable `centered_price` containing a version of the `price` column with the mean price subtracted.

(Note: this 'centering' transformation is a common preprocessing step before applying various machine learning algorithms.)

In [64]:
mean_price = reviews["price"].mean()
centered_price = reviews["price"] - mean_price
centered_price

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [65]:
def recenter_price(row):
    row.price = row.price - mean_price
    return row

In [66]:
ceneterd_price = reviews.apply(recenter_price, axis = 1)

In [67]:
ceneterd_price

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,-20.363389,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,-21.363389,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,-22.363389,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,29.636611,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,-7.363389,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,39.636611,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,-5.363389,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,-3.363389,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,-14.363389,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## 5.
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable `bargain_wine` with the title of the wine with the highest points-to-price ratio in the dataset.

Hint: The idxmax method may be useful here.

In [68]:
bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, ["title"]]
bargain_wine

title    Bandit NV Merlot (California)
Name: 64590, dtype: str

## 6.
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series `descriptor_counts` counting how many times each of these two words appears in the `description` column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

In [69]:
# Below solution is incorrect, ignore
def count_words(row):
    row["tropical_count"] = 0
    row["fruity_count"] = 0

    words = [word.lower() for word in row["description"].strip().split()]

    if "tropical" in words:
        row["tropical_count"] += 1

    if "fruity" in words:
        row["fruity_count"] += 1

    return row

In [70]:
#reviews.apply(count_words, axis = 1)

In [71]:
n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])

In [72]:
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [73]:
n_trop

np.int64(3607)

## 7.
We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series `star_ratings` with the number of stars corresponding to each review in the dataset.

In [92]:
def ratings(row):

    if row.points >= 95:
        return 3
    elif row.points >= 85 and row.points < 95:
        return 2
    else:
        return 1

    if row.country == "Canada": #if row.country.lower() == "canada":
        return 3

In [ ]:
reviews.country = reviews.country.dropna()

In [94]:
(reviews.country.isnull() == True).value_counts() # notice that this is still not dropping NA values
# In the ratings function, I was using lower() on country column, and beacuse of NA values, it kept getting error

country
False    129908
True         63
Name: count, dtype: int64

In [95]:
star_ratings = reviews.apply(ratings, axis='columns')

In [96]:
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

## Why `dropna()` did not remove the `NaN` values from `reviews.country`

`dropna()` is working correctly, but not in the way it might appear at first.  
This happens because of **how pandas aligns indices when assigning a Series back to a DataFrame column**.

### What `dropna()` actually does

When running:

```python
reviews.country = reviews.country.dropna()
```

`reviews.country.dropna()` returns a **Series with the NaN rows removed**, but it **keeps the original index values**.

Example:

```
Original Series

index  country
0      US
1      NaN
2      Canada
3      France
```

After `dropna()`:

```
index  country
0      US
2      Canada
3      France
```

Notice that **index 1 is missing**, but the index numbers themselves are not reset.

### What happens during assignment

When assigning this Series back:

```python
reviews.country = reviews.country.dropna()
```

pandas **aligns values by index**:

```
reviews DataFrame

index  country
0      US
1      NaN
2      Canada
3      France
```

Since row **1 still exists in the DataFrame**, pandas fills it with `NaN` again.

Therefore, it may look like `dropna()` did not work, but in reality the DataFrame rows were never removed.

---

## Correct ways to remove the null values

### Option 1 (Recommended): Drop rows from the DataFrame

```python
reviews = reviews.dropna(subset=['country'])
```

This removes all rows where `country` is `NaN`.

---

### Option 2: Handle `NaN` safely in the function

```python
import pandas as pd

def ratings(row):
    if row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

    if pd.notnull(row.country) and row.country.lower() == "canada":
        return 3
```

---

### Option 3: Use pandas string operations

Convert to pandas' nullable string type:

```python
reviews.country = reviews.country.astype("string")
```

Or use the `.str` accessor:

```python
reviews.country.str.lower()
```

`.str` methods automatically **ignore `NaN` values**, preventing errors like:

```
AttributeError: 'float' object has no attribute 'lower'
```

---

## Additional issue in the `ratings` function

In the current function:

```python
def ratings(row):
    if row.points >= 95:
        return 3
    elif row.points >= 85 and row.points < 95:
        return 2
    else:
        return 1

    if row.country.lower() == "canada":
        return 3
```

The `country` condition is **never executed**.

This is because the earlier `return` statements exit the function before the code reaches that condition.  
This makes the last `if` block **unreachable code**.

---

## Recommended Kaggle-style fix

The simplest and most common approach is:

```python
reviews = reviews.dropna(subset=['country'])
```

This ensures the column contains no `NaN` values before applying operations like `.lower()`.